"[JSON]":
  - changed-files:
    - any-glob-to-any-file: "**/*.json"

"[YML]":
  - changed-files:
    - any-glob-to-any-file: "**/*.yml"

"[PHP]":
  - changed-files:
    - any-glob-to-any-file: "**/*.php"

"[Javascript]":
  - changed-files:
    - any-glob-to-any-file: "**/*.js"

"[blade]":
  - changed-files:
    - any-glob-to-any-file: "**/*.blade.php"

"[Markdown]":
  - changed-files:
    - any-glob-to-any-file: "**/*.md"

"[Python]":
  - changed-files:
    - any-glob-to-any-file: "**/*.py"

"<Documentation>":
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.md"
      - "doc/**/*"
      - "doxygen_doc/**/*"

"Code: Tooling":
  - changed-files:
    - any-glob-to-any-file: ".github/**/*"

"Code: Tests":
  - changed-files:
    - any-glob-to-any-file: "tests/**/*"

"Models":
  - changed-files:
    - any-glob-to-any-file: "**/Models/**"
