name: Run scanner
on:
  workflow_dispatch:
    inputs:
      url:
        description: "Url to check"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 'pypy3.8' ]
    steps:

      - name: Value
        run: echo ${{ github.event.inputs.url }}
