name: Run scanner
on:
  workflow_dispatch:
    inputs:
      url:
        description: "Url to check"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 'pypy3.8' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install selenium
        run: pip install selenium
      - name: Install webdriver-manager
        run: pip install webdriver-manager
      - name: Install requests
        run: pip install requests
      - name: Install requests
        run: pip install alive-progress

      - name: Scan
        run: python main.py u=${{ github.event.inputs.url }}
