name: vulnerabilities scanner
on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Urls to packages"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 'pypy3.8' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install wget
        run: pip install wget
      - name: Install datetime
        run: pip install datetime
      - name: Install snyk
        run: |
          npm install snyk -g
      - name: Scan
        run: python vulnerabilities-scanner.py ${{ github.event.inputs.urls }}
