name: vulnerabilities scanner
on:
  workflow_dispatch:
    inputs:
      urls:
        description: "Urls to packages"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 'pypy3.8' ]
    steps:
      - uses: snyk/actions/setup@master
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Scan
        run: python vulnerabilities-scanner.py ${{ github.event.inputs.urls }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
